### PR TITLE
Used some js to make the the world "Course" append the 's' character …

### PR DESCRIPTION
**Pull request by Technerder**
…if the user has created more than 1 course. (Untested)

### CODE REVIEW

**Comment by presidentennn** [comment]
Doesn't make a lot of sense to me.

**Comment by Technerder** [comment]
It uses a tertiary operator to append an 's' to the end of the word 'Course'

So:

The first number being the amount of courses the user has.

0 : '0 Courses'
1 : '1 Course'
2 : '2 Courses'
 
and so on.

**Comment by presidentennn** [comment]
Well, I understood that, but I was wondering why we need this. I'm assuming you want to avoid the "1 Course" text appearing (which is wrong grammatically)?

**Comment by timtomtim7** [comment]
> 
> 
> Well, I understood that, but I was wondering why we need this. I'm assuming you want to avoid the "1 Course" text appearing (which is wrong grammatically)?

Well, it's definitely not meant to be "1 Courses" or "2 Course"

**Comment by presidentennn** [comment]
It's not supposed to be a number before "Course(s)" so I'm not sure where you got that from.
A better idea would be to have the text "Courses (5)" which follows the format from other places (for example the courses/show page.

**Comment by Technerder** [comment]
I personally believe that '5 Courses' is better than 'Courses (5)', and I feel like quite a few others feel the same.

**Comment by presidentennn** [comment]
"Courses", "Comments" and "Sections" are supposed to be subtitles. It would make much more sense if this format below was written everywhere (it already exists on most pages) instead of having mixed formats.
image

**Comment by timtomtim7** [comment]
I wasn't paying attention to where it was on the page, sorry.

**Comment by Technerder** [comment]
Fair point.

**Pull request closed without merging**
